# Generated by Django 5.0.6 on 2024-07-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_entry_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="owner",
        ),
    ]
